name: ghcr.io
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 for deploy to GitHub Container Registry
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: ghcr.io

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish to GitHub Container Registry
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build -Dimage=ghcr.io/fred4jupiter/fredbet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}